name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Verify tag matches package.json version
        id: verify
        run: |
          TAG_VERSION="${GITHUB_REF##*/}" # refs/tags/v0.1.0 -> v0.1.0
          TAG_VERSION_STRIPPED="${TAG_VERSION#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Tag version: $TAG_VERSION_STRIPPED"
            echo "Package version: $PKG_VERSION"
          if [ "$TAG_VERSION_STRIPPED" != "$PKG_VERSION" ]; then
            echo "::error::Tag version ($TAG_VERSION_STRIPPED) does not match package.json version ($PKG_VERSION)";
            exit 1;
          fi
          echo "version=$PKG_VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build --silent

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.verify.outputs.version }}
          name: v${{ steps.verify.outputs.version }}
          body: |
            Automated release for version v${{ steps.verify.outputs.version }}.
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
